import Config

# Configure your database
# DATABASE_HOST env var allows overriding for Docker (e.g., "db" for docker-compose)
config :doctrans, Doctrans.Repo,
  username: "postgres",
  password: "postgres",
  hostname: System.get_env("DATABASE_HOST", "localhost"),
  database: "doctrans_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Doctrans is a local, single-user app with no authentication, so the development
# endpoint binds on loopback only. PHX_BIND_IP is the one explicit way to widen
# that: PHX_BIND_IP=0.0.0.0 (or :: for IPv6) accepts connections on every
# interface, which is what a container needs and what reaches the app from a
# trusted LAN — you do so at your own risk, since there is no auth to pass.
#
# The binding deliberately no longer follows DATABASE_HOST. Pointing development
# at a database on another host says nothing about who should be able to reach
# the *app*, and deriving one from the other meant that changing where Postgres
# lives silently published an unauthenticated app on every interface.
#
# The value has to be parsed here rather than passed through: Bandit types `:ip`
# as `:inet.socket_address()` and hands it to `:gen_tcp.listen/2`, which exits
# with :badarg on a binary, so a textual address stops the endpoint from ever
# starting. `:inet.parse_address/1` takes a charlist and accepts IPv4 and IPv6
# literals alike; it resolves no host names, which is why the error below says so.
#
# This repeats the same parse that `config/runtime.exs` performs for :prod, and
# it has to: this file is evaluated before the project's own modules are
# compiled, so it cannot call a shared helper module, and a release ships only
# `config/runtime.exs`, so a sibling file pulled in with `Code.require_file/1`
# would simply not be there. Removing the duplication breaks one side or the
# other, so the two copies are kept deliberately in step instead.
bind_ip_string = System.get_env("PHX_BIND_IP") || "127.0.0.1"

bind_ip =
  case :inet.parse_address(String.to_charlist(bind_ip_string)) do
    {:ok, address} ->
      address

    {:error, _reason} ->
      raise "PHX_BIND_IP must be an IPv4 or IPv6 address literal, got: #{bind_ip_string}. " <>
              "Use 127.0.0.1 to bind on loopback, 0.0.0.0 (or :: for IPv6) to accept " <>
              "connections on every interface. Host names are not resolved."
  end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :doctrans, DoctransWeb.Endpoint,
  http: [
    # Loopback unless PHX_BIND_IP says otherwise; see the note above.
    ip: bind_ip,
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "GYS0LjJXZ97Vk+1tcnCCkwCPuhjrtN19jjj+BykXjcyKpvk6d+jnv3uqJ8bXZ02v",
  live_view: [signing_salt: "LkQv8tR2wXz0mB5nY6uP3fA7dJ1cE9gH"],
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:doctrans, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:doctrans, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :doctrans, DoctransWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/doctrans_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for the dashboard
config :doctrans, dev_routes: true

# Include timestamps and metadata in development logs for debugging
config :logger, :default_formatter,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id, :mfa]

# Set log level to debug in development
config :logger, level: :debug

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
