defmodule DoctransWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :doctrans

  # The session is stored in a cookie that is both signed and encrypted,
  # so its contents cannot be read or tampered with.
  @session_options [
    store: :cookie,
    key: "_doctrans_key",
    signing_salt: "Qr5ZNHs0",
    encryption_salt: "Zm5XkR8p",
    same_site: "Lax",
    secure: Application.compile_env(:doctrans, :env) == :prod,
    http_only: true
  ]

  # Hard server-side limit for multipart bodies: the upload UI allows up to
  # 10 files of `:max_file_size` each, so allow headroom above that.
  # Keep this compile-time read so Mix tracks changes to the parser limit.
  # It uses the same required setting as Config.Uploads.max_file_size/0.
  @multipart_length fn ->
    max_file_size =
      Application.compile_env!(:doctrans, [:uploads, :max_file_size])

    10 * max_file_size + 1_000_000
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :doctrans,
    gzip: not code_reloading?,
    only: DoctransWeb.static_paths()

  # Serve generated page images only; retained sources and converted PDFs
  # share the upload root but must never be exposed by static serving.
  # These contain private document content: prevent browser/proxy storage,
  # including requests with Plug.Static's versioned query strings.
  plug DoctransWeb.Plugs.UploadImages,
    at: "/uploads",
    from: {:doctrans, "priv/static/uploads"},
    gzip: false,
    cache_control_for_etags: "private, no-store",
    cache_control_for_vsn_requests: "private, no-store"

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :doctrans
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    length: @multipart_length.(),
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DoctransWeb.Router
end
