defmodule DoctransWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :doctrans

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_doctrans_key",
    signing_salt: "Qr5ZNHs0",
    same_site: "Lax",
    secure: Application.compile_env(:doctrans, :env) == :prod,
    http_only: true
  ]

  # Hard server-side limit for multipart bodies: the upload UI allows up to
  # 10 files of `:max_file_size` each, so allow headroom above that.
  # (`:uploads` is static config, never overridden at runtime.)
  @multipart_length fn ->
    max_file_size =
      Application.compile_env(:doctrans, :uploads, [])[:max_file_size] || 100_000_000

    10 * max_file_size + 1_000_000
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :doctrans,
    gzip: not code_reloading?,
    only: DoctransWeb.static_paths()

  # Serve uploaded page images from priv/static/uploads.
  # Original source files are deleted after extraction, so only derived
  # page images are ever served from this directory.
  plug Plug.Static,
    at: "/uploads",
    from: {:doctrans, "priv/static/uploads"},
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :doctrans
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    length: @multipart_length.(),
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DoctransWeb.Router
end
